### ISSUE TITLE
How can I solve the following error? The model was downloaded from Huggingface

### ISSUE THREAD

**Issue by xcssgzs** [OpenBMB/ToolBench#10]
Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\pydevd.py", line 1496, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm Community Edition 2022.3.3\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\PycharmProjects\ToolBench\toolbench\inference\inference_single_tool.py", line 122, in <module>
    main()
  File "D:\PycharmProjects\ToolBench\toolbench\inference\inference_single_tool.py", line 112, in main
    customllm = LoraModel(base_name_or_path=args.model_path, model_name_or_path=args.lora_path)
  File "d:\pycharmprojects\bmtools\bmtools\models\lora_model.py", line 18, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(base_name_or_path, use_fast=False)
  File "D:\ProgramData\Python\Python39\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 655, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class LlamaTokenizer does not exist or is not currently imported.

Process finished with exit code 1

**Comment by xcssgzs** [comment]
> Which version of transformers are you using?
@pooruss The version of the transformers are 4.26.1

**Comment by xcssgzs** [comment]
@pooruss Thank you!
