### ISSUE TITLE
rapidapi.py异常 TypeError: unhashable type: 'dict'

### ISSUE THREAD

**Issue by taiyouZhang** [OpenBMB/ToolBench#80]
调试现状如下
![image](https://github.com/OpenBMB/ToolBench/assets/13816934/1eed7ce1-6d3f-4af6-ac14-1dc1096f47fa)

在UI界面输入“What is the weather in New York today?”，会出现以下问题
```Python
Finished with future
Debugging middleware caught exception in streamed response at a point where response headers were already sent.
Traceback (most recent call last):
  File "/root/anaconda3/envs/py3_10/lib/python3.10/site-packages/werkzeug/wsgi.py", line 289, in __next__
    return self._next()
  File "/root/anaconda3/envs/py3_10/lib/python3.10/site-packages/werkzeug/wrappers/response.py", line 32, in _iter_encoded
    for item in iterable:
  File "/root/anaconda3/envs/py3_10/lib/python3.10/site-packages/flask/helpers.py", line 118, in generator
    yield from gen
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/toolbench_server.py", line 147, in generate
    future.result()
  File "/root/anaconda3/envs/py3_10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/root/anaconda3/envs/py3_10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/root/anaconda3/envs/py3_10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/toolbench_server.py", line 52, in run_pipeline
    self.pipeline.run_single_task(
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 500, in run_single_task
    env = rapidapi_wrapper(data_dict, tool_des, retriever, args, process_id=process_id)
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 84, in __init__
    tool_descriptions = self.build_tool_description(data_dict)
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 138, in build_tool_description
    tool_des = contain(origin_tool_names,white_list)
  File "/root/workspace/taiyou.zhang/ToolLLM/ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py", line 52, in contain
    output.add(white_list[cand])
TypeError: unhashable type: 'dict'
```

尝试打印对应的cand变量和white_list[cand]变量，结果如下：
```
candidate_list= ['weather_v14', 'weather_api_by_any_city', 'currencyconverter', 'weatherapi_com', 'test']
cand = 'weather_v14 '
white_list[cand] = {'description': 'weather forecast', 'standard_tool_name': 'weather_v14'}
```
可能涉及问题的代码在`ToolBench/toolbench/inference/Downstream_tasks/rapidapi.py`
```
def contain(candidate_list, white_list):
    output = set()
    for cand in candidate_list:
        if cand in white_list:
            output.add(white_list[cand])
        else:
            return False
    return list(output)
```

**Comment by pooruss** [comment]
您好，该问题已修复，详见https://github.com/OpenBMB/ToolBench/blob/master/toolbench/inference/Downstream_tasks/rapidapi.py#L45

**Comment by taiyouZhang** [comment]
感谢非常高效的支持
